### ISSUE TITLE
Calculate centrality for specific vertices only?

### ISSUE THREAD

**Issue by mbojan** [schochastics/netrankr#1]
Great! Thanks for that!

One suggestion, at least for the index-calculating functions. I think it would make sense if they all would share the same first two arguments:

1. The graph.
2. Vertex ids for which the index will be calculated.

Just like `igraph::betweenness` for example. If one is interested in scores for only subset of vertices, or specific vertex, it will speed-up computation quite a bit.

**Comment by schochastics** [comment]
thanks for the suggestion. My personal TODO list already includes a point to make everything more consistent with `igraph`. Once all the (potential) initial bugs are fixed I am gonna start on that
