### ISSUE TITLE
benchmarking code

### ISSUE THREAD

**Issue by corybrunson** [schochastics/netrankr#13]
The benchmarking vignette is compelling (and the availability of approximation methods is impressive), but i am unable to check the results for lack of source code. Certainly the vignette should not itself reproduce this analysis, but i believe the code, or code for a smaller, illustrative benchmarking test, should be included—with the repository if not with the package, e.g. in a folder ignored by the R build.

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4563)._

**Comment by schochastics** [comment]
This is a very good point that I missed. I added replication material in the `data-raw` folder. This is not the material I used back when I added the vignette (I was oblivious about reproducible code then) but from a more recent project. The results dont change, but I did change the figures in the vignette to reflect the different benchmark dataset.

**Comment by corybrunson** [comment]
This is great, thank you! I only further request that the benchmarking vignette tell users where to find this script so that they can run and adapt it as needed.
