### ISSUE TITLE
Installation failure due to dependency on >= R-3.6

### ISSUE THREAD

**Issue by tedmoorman** [schochastics/netrankr#9]
In the installation, I'm receiving the following error message: `Error : object ‘hcl.colors’ is not exported by 'namespace:grDevices'`. [This was a new feature in R-3.6](https://bookdown.org/hneth/ds4psy/D-3-apx-colors-basics.html#apx:hcl-color-palettes) .  Is there an archived version compatible with R-3.5?

**Comment by schochastics** [comment]
Wasn't aware that this is a newish feature. 7 will revert this dependency in n upcoming bugfix release

**Comment by tedmoorman** [comment]
For those of us who aren't network analytics scholars, I'm really appreciative of such a critical tool. Thank you so much for developing this!
